server:
  port: 8887

github:
  client:
    id: 49d0a583ad7ef700f872
    secret: 719e000662aba291ac0dfdf20e4dac1417ba0e3a
  redirect:
    uri: http://localhost:8887/callback

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/community?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver