server:
  port: 8887

github:
  client:
    id: 49d0a583ad7ef700f872
    secret: 719e000662aba291ac0dfdf20e4dac1417ba0e3a
  redirect:
    uri: http://localhost:8887/callback

spring:
  datasource:
    url: jdbc:h2:~/community
    username: sa
    password: 123
    driver-class-name: org.h2.Driver